'use client';

import { Artifact } from '@/app/page';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { Prism as SyntaxHighlighter } from 'react-syntax-highlighter';
import { vscDarkPlus } from 'react-syntax-highlighter/dist/esm/styles/prism';

type CanvasRendererProps = {
  artifact: Artifact | null;
};

export const CanvasRenderer = ({ artifact }: CanvasRendererProps) => {
  if (!artifact?.isVisible) {
    return (
      <div className="flex h-full items-center justify-center bg-white">
        <div className="text-center">
          <h2 className="text-lg font-medium text-gray-500">The Canvas</h2>
          <p className="text-sm text-gray-400">Content generated by the AI will appear here.</p>
        </div>
      </div>
    );
  }

  return (
    <div className="h-full bg-white p-6 shadow-sm overflow-y-auto">
      <h1 className="text-2xl font-bold mb-4">{artifact.title}</h1>
      {artifact.type === 'markdown' && (
        <div className="prose prose-sm max-w-none">
          <ReactMarkdown
            remarkPlugins={[remarkGfm]}
            components={{
              code({ node, className, children, ...props }) {
                const match = /language-(\w+)/.exec(className || '');
                return match ? (
                  <SyntaxHighlighter
                    style={vscDarkPlus}
                    language={match[1]}
                    PreTag="div"
                  >
                    {String(children).replace(/\n$/, '')}
                  </SyntaxHighlighter>
                ) : (
                  <code className={className} {...props}>
                    {children}
                  </code>
                );
              },
            }}
          >
            {artifact.content}
          </ReactMarkdown>
        </div>
      )}
      {artifact.type === 'code' && (
         <SyntaxHighlighter
            style={vscDarkPlus}
            language="javascript" // Defaulting to JS for now
            PreTag="div"
          >
            {artifact.content}
        </SyntaxHighlighter>
      )}
    </div>
  );
};
